markdown: redcarpet
baseurl: "/maffan" # the subpath of your site, e.g. /blog/
url: "https://maffan" # the base hostname & protocol for your site
github_username:  affan00

# Build settings
markdown: kramdown
